services:

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d   # Optional: SQL init scripts
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-appuser} -d ${POSTGRES_DB:-myappdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://{PG_HOST}:{PG:PORT}/${PG_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA / Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update          # use 'validate' in production
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

      # Active profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

# Volumes & Networks
volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge