name: Preview workflow

on: 
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  build_preview:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7